name: practice
description: "practice nike project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  hive_flutter: ^1.1.0
  webview_flutter: ^4.13.0
  flutter_gen: ^5.11.0
  go_router: ^16.2.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/fonts/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700